version: "3"

services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python3 app.py
    expose:
      - "5000"
    ports:
      - 5000:5000
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
