apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: tidehackathon.postgres.database.azure.com
    database: iodashboard
    user: tidereader
    secureJsonData:
      password: "ioH@ck@thonReader2023!"
    jsonData:
      sslmode: "require" # disable/require/verify-ca/verify-full
      maxOpenConns: 0         # Grafana v5.4+
      maxIdleConns: 2         # Grafana v5.4+
      connMaxLifetime: 14400  # Grafana v5.4+
      postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false